sudo: required
services:
  - docker


before_install:
  - docker build -t skswami91/react-tests -f ./client/Dockerfile.dev ./client


script:
  - docker run -e CI=true skswami91/react-tests npm test -- --coverage

after_success:
  - docker build -t skswami91/multi-client ./client
  - docker build -t skswami91/multi-server ./server
  - docker build -t skswami91/multi-worker ./worker
  - docker build -t skswami91/multi-nginx ./nginx
#login to the Docker CLI
  - echo "$DOCKER_PASSWORD"|docker login -u "$DOCKER_ID" --password-stdin
#push the images to dockerhub
  - docker push skswami91/multi-client
  - docker push skswami91/multi-server
  - docker push skswami91/multi-worker
  - docker push skswami91/multi-nginx
deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker-multi-container"
  env: "DockerMultiContainer-env"
  bucket_name: "elasticbeanstalk-ap-southeast-1-887637364220"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
